name: Check All

on: [push, pull_request]

jobs:
  build-firmware:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive

      - name: Print Python Version
        run: |
          python3.8 --version

      - name: Install Python Modules
        run: |
          pip3 install simpleparse

     - name: Build Docker
       run: |
         bash step1-build-docker.sh
